# Generated by spec2scl 1.1.3-3 and then updated based on:
#  * rh-python35 metapackage spec file
#  * softwarecollections.org/en/docs/guide (section 4.1.1. Using an scldevel
#    Subpackage in a Dependent Software Collection)
#  * https://developerblog.redhat.com/2014/12/04/add-packages-to-python-2-7-software-collection
#  * section 4.2. Extending the python27 and rh-python34 Software Collections
#    from https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/2/html-single/Packaging_Guide/index.html#chap-Extending_Red_Hat_Software_Collections

%global scl_name_prefix rh-
%global scl_name_base usmqetools
%global scl_name_version 10
%global scl %{scl_name_prefix}%{scl_name_base}%{scl_name_version}

%scl_package %scl

# Defaults for the values for the python35 Software Collection. These
# will be used when python35-scldevel is not in the buildroot
%{!?scl_python:%global scl_python python35}
%{!?scl_prefix_python:%global scl_prefix_python %{scl_python}-}

# Only for this build, you need to override default __os_install_post,
# because the default one would find /opt/.../lib/python3.5/ and try
# to bytecompile with the system /usr/bin/python3.5
# TODO: should I use %{scl_python} or %{scl_no_vendor} here?
%global __os_install_post %{%{scl_python}_os_install_post}
# Similarly, override __python_requires for automatic dependency generator
%global __python_requires %{%{scl_python}_python_requires}

# The directory for site packages for this Software Collection
# TODO: can I use just %{scl} instead of rh-usmqetools10 here?
%global usmqetools10_sitelib %(echo %{python35python_sitelib} | sed 's|%{scl_python}|%{scl}|')

## General notes about python3x SCL packaging
# - the names of packages are NOT prefixed with 'python3-' (e.g. are the same as in Fedora)
# - the names of binaries of Python 3 itself are both python{-debug,...} and python3{-debug,...}
#   so both are usable in shebangs, the non-versioned binaries are preferred.
# - the names of other binaries are NOT prefixed with 'python3-'.
# - there are both macros in '3' variant and non-versioned variant, e.g. both %%{__python}
#   and %%{__python3} are available

# reused from rh-python35
%global nfsmountable 1
%global _turn_off_bytecompile 1

%global install_scl 1

# Do not produce empty debuginfo package.
%global debug_package %{nil}

Summary: Package that installs %scl
Name: %scl_name
Version: 1.0
Release: 1%{?dist}
License: GPLv2+
Source1: README
Source2: LICENSE
BuildRequires: help2man
BuildRequires: scl-utils-build
BuildRequires: %{scl_prefix_python}scldevel
# Require python35-python-devel, we will need macros from that package
BuildRequires: %{scl_prefix_python}python-devel
Requires: %{scl_prefix}python-versiontools
%if 0%{?install_scl}
# Put your scl requires here
%endif

%description
This is the main package for %scl Software Collection.

%package runtime
Summary: Package that handles %scl Software Collection.
Requires: scl-utils
Requires: %{scl_prefix_python}runtime

%description runtime
Package shipping essential scripts to work with %scl Software Collection.

%package build
Summary: Package shipping basic build configuration
Requires: scl-utils-build
Requires: %{scl_prefix_python}scldevel

%description build
Package shipping essential configuration macros to build %scl Software Collection.

%package scldevel
Summary: Package shipping development files for %scl

%description scldevel
Package shipping development files, especially usefull for development of
packages depending on %scl Software Collection.

%prep
%setup -T -c

# This section generates README file from a template and creates man page
# from that file, expanding RPM macros in the template file.
cat >README <<'EOF'
%{expand:%(cat %{SOURCE1})}
EOF

# copy the license file so %%files section sees it
cp %{SOURCE2} .

%build
# generate a helper script that will be used by help2man
cat >h2m_helper <<'EOF'
#!/bin/bash
[ "$1" == "--version" ] && echo "%{scl_name} %{version} Software Collection" || cat README
EOF
chmod a+x h2m_helper

# generate the man page
help2man -N --section 7 ./h2m_helper -o %{scl_name}.7
# Fix single quotes in man page. See RHBZ#1219531
#
# http://lists.gnu.org/archive/html/groff/2008-06/msg00001.html suggests that
# using "'" for quotes is correct, but the current implementation of man in 6
# mangles it when rendering.
sed -i "s/'/\\\\(aq/g" %{scl_name}.7

%install
%scl_install
# Create the enable scriptlet
cat >> %{buildroot}%{_scl_scripts}/enable << EOF
. scl_source enable %{scl_python}
export PYTHONPATH=%{usmqetools10_sitelib}\${PYTHONPATH:+:\${PYTHONPATH}}
export PATH=%{_bindir}\${PATH:+:\${PATH}}
export LD_LIBRARY_PATH=%{_libdir}\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}
export MANPATH=%{_mandir}:\${MANPATH}
export PKG_CONFIG_PATH=%{_libdir}/pkgconfig\${PKG_CONFIG_PATH:+:\${PKG_CONFIG_PATH}}
export XDG_DATA_DIRS="%{_datadir}:\${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
EOF

mkdir -p %{buildroot}%{usmqetools10_sitelib}

# - Enable Software Collection-specific bytecompilation macros from
#   the python35-python-devel package.
# - Also override the %%python_sitelib macro to point to the rh-usmqetools10
#   Software Collection.
# - If you have architecture-dependent packages, you will also need to override
#   the %%python_sitearch macro.

cat >> %{buildroot}%{_root_sysconfdir}/rpm/macros.%{scl}-config << EOF
%%scl_package_override() %%{expand:%{?python35_os_install_post:%%global __os_install_post %%python35_os_install_post}
%%global __python_requires %%python35_python_requires
%%global __python_provides %%python35_python_provides
%%global __python %python35__python
%%global python_sitelib %{usmqetools10_sitelib}
%%global python3_sitelib %{usmqetools10_sitelib}
}
EOF


# Create the scldevel subpackage macros
cat >> %{buildroot}%{_root_sysconfdir}/rpm/macros.%{scl_name_base}-scldevel << EOF
%%scl_%{scl_name_base} %{scl}
%%scl_prefix_%{scl_name_base} %{scl_prefix}
EOF


# install generated man page
mkdir -p %{buildroot}%{_mandir}/man7/
install -m 644 %{scl_name}.7 %{buildroot}%{_mandir}/man7/%{scl_name}.7

%files
%if 0%{?rhel} <= 6
%files runtime
%else
%files runtime -f filesystem
%endif
%doc README LICENSE
%scl_files
%{usmqetools10_sitelib}
%{_mandir}/man7/%{scl_name}.*

%files build
%{_root_sysconfdir}/rpm/macros.%{scl}-config

%files scldevel
%{_root_sysconfdir}/rpm/macros.%{scl_name_base}-scldevel

%changelog
* Wed Nov 09 2016 Martin Bukatovic <mbukatov@redhat.com> - 1.0-1
- Initial package.
